
openapi: 3.1.1
info:
  title: SchedulerGPT API
  version: "1.0.3"
servers:
  - url: https://pieces-gmt-pearl-lynn.trycloudflare.com
security:
  - XApiKey: devkey123
paths:
  /health:
    get:
      operationId: health
      summary: Health check
      security: []  # no API key required for health
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
  /schedule/preview:
    post:
      operationId: schedule_preview
      summary: Build a 1-week schedule without saving
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScheduleRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  days: { type: integer }
                  jobs: { type: integer }
                  schedule: { type: array, items: { type: object } }
  /schedule/commit:
    post:
      operationId: schedule_commit
      summary: Build and save a 1-week schedule
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScheduleRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  days: { type: integer }
                  jobs: { type: integer }
                  schedule: { type: array, items: { type: object } }
  /jobs/search:
    get:
      operationId: jobs_search
      summary: Search unscheduled jobs with optional region/SOW/horizon/radius filters
      parameters:
        - in: query
          name: region
          schema: { type: string }
        - in: query
          name: sow
          schema: { type: string }
        - in: query
          name: horizon_days
          schema: { type: integer }
        - in: query
          name: tech_id
          schema: { type: integer }
        - in: query
          name: radius_miles
          schema: { type: number }
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  count: { type: integer }
                  rows: { type: array, items: { type: object } }
components:
  securitySchemes:
    XApiKey:
      type: apiKey
      in: header
      name: X-API-Key
  schemas:
    ScheduleRequest:
      type: object
      properties:
        tech_id: { type: integer }
        start_date: { type: string, format: date, example: "2025-09-01" }
        assigned_clusters: { type: array, items: { type: integer } }
        priority_work_orders: { type: array, items: { type: integer } }
        horizon_days: { type: integer, default: 21 }
        target_sow_list: { type: array, items: { type: string } }
        anchor_week_strategy: { type: string, default: "exhaustive" }
        allow_in_day_filler: { type: boolean, default: true }
        fixed_jobs: { type: array, items: { type: object } }
        weekly_target_hours_min: { type: integer, default: 45 }
        weekly_target_hours_max: { type: integer, default: 50 }
        max_drive_minutes: { type: integer, default: 60 }
        pre_night_day_job_cap: { type: integer, default: 4 }
        radius_miles_cap:
          type: [integer, "null"]
          default: 250
        seed_region:
          type: [string, "null"]
        seed_cluster:
          type: [integer, "null"]
      required: [tech_id, start_date]
